version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "production"
      