version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    ignore:
      - dependency-name: "eslint"
        versions: [">=10.0.0 <11.0.0"]
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns: []
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    ignore:
      - dependency-name: "eslint"
        versions: [">=10.0.0 <11.0.0"]
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns: []
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    ignore:
      - dependency-name: "eslint"
        versions: [">=10.0.0 <11.0.0"]
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns: []
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/upload-artifact"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      dependencies:
        patterns:
          - "*"
